---

#####################################################################################
resources:

# Docker
- name: git-example
  type: git
  source:
    uri: https://github.com/vergissberlin/t3cmd.git

- name: docker-example
  type: docker-image
  source:
    repository: vergissberlin/t3cmd

- name: docker-alpine
  type: docker-image
  source:
    repository: alpine

# Others
- name: notify
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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


#####################################################################################
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

#####################################################################################
jobs:

- name: test
  plan:
  - get: git-example
    trigger: true
  - get: docker-alpine
    trigger: true
  - task: test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: docker-alpine
      outputs:
      - name: out
      run:
        path: sh
        args:
        - -exc
        - |
          echo "This is from mqtt-concource ci ressource" > out/message
  on_failure:
    put: notify
    params:
      text: "Test failed"
  on_error:
    put: notify
    params:
      text: "Test errored"
  on_abort:
    put: notify
    params:
      text: "Test aborted"


- name: build
  plan:
  - get: git-example
    trigger: true
    passed:
    - test
  - get: docker-example
  on_failure:
    put: notify
    params:
      text: "Build failed"
  on_error:
    put: notify
    params:
      text: "Build errored"
  on_abort:
    put: notify
    params:
      text: "Build aborted"
  on_success:
    put: notify
    params:
      text: "Build succeeded"
